server:
  port: 8090

spring:
  application:
    name: spring-debezium-kafka

  datasource:
    url: jdbc:postgresql://localhost:5432/demo-debezium
    username: debezium
    password: 123456

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:29092

  data:
    redis:
      host: localhost
      port: 6379

  threads:
    virtual:
      enabled: true

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.data.redis: DEBUG
